# Generated by Django 5.0 on 2023-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail')], max_length=200)),
                ('unique_client_id', models.CharField(default='1703687636708', max_length=50, unique=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('key_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('company_history', models.TextField()),
                ('contactTerm', models.CharField(choices=[(6, '6 Months'), (9, '9 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months'), (0, 'Unlimited')], default=0, max_length=20)),
                ('company_logo', models.ImageField(upload_to='company_logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
