# Generated by Django 5.0 on 2024-01-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_alter_client_unique_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="unique_client_id",
            field=models.CharField(default="1705286820315", max_length=50, unique=True),
        ),
    ]
