# Generated by Django 5.0 on 2024-01-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(default="1705286065996", max_length=50, unique=True),
        ),
    ]
