# Generated by Django 5.0 on 2024-01-15 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_officebranch_customuser_client_customuser_branch"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
