# Generated by Django 5.0 on 2024-01-15 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
